### PR TITLE
Added RSS icon

### PR DESCRIPTION
**Pull request by Mehvix**
Adds an RSS icon next the username on blog pages. Icon is from [Bootstrap](https://icons.getbootstrap.com/icons/rss-fill/). RSS generator code is [here](https://github.com/Mehvix/aops-blog-rss).

### 1 ([src](https://artofproblemsolving.com/community/c1248416))
image 

### 2 ([src](https://artofproblemsolving.com/community/c1273888))
image

### CODE REVIEW

**Comment by epiccakeking** [comment]
There is no reason to add such an icon.

**Comment by Mehvix** [comment]
I would disagree – it's fairly common for web blogs to have an RSS icon on the page. Would this be reasonable if it were toggleable in the options?

**Comment by epiccakeking** [comment]
Maybe if it was toggleable and had clear indication that the RSS feed is provided by a third party.

Perhaps I should explain my position better. The old version of the userscript (v5) had the stated purpose to "enhance existing features of the website." Although this isn't quite accurate, I primarily intend to only include features that do not rely on external resources to function. Although an RSS icon could be useful for people who still have use for RSS, I do not think the tradeoff of having a feature that depends on a website other than AoPS is worth the benefit of having an RSS feed from said website more easily available.

Personally I would suggest that you just create your own seperate userscript for adding RSS icons.

**Comment by Mehvix** [comment]
Ahh I understand, thanks for the clarification. I'll maintain my fork with the RSS code.

**Pull request closed without merging**
