### PR TITLE
New Darkmode

### PR DESCRIPTION
**Pull request by darkwater4213**
NOTE: This is code copied straight from Darkreader. I'm working on putting LaTeX compatibility in as well, but that might take a while. I'm not very active, so it might take a while before all the unnecessary parts are weeded out. I'm leaving some more popular websites in this (like YouTube, DuckDuckGo, etc.) so it makes those darker as well. (You'll need to enable it as global, I think)

You might also need the API from [darkreader/darkreader](https://github.com/darkreader/darkreader). (I honestly have no idea. I will be testing it though, so I keep you posted)

### CODE REVIEW

**Comment by epiccakeking** [comment]
The entire point of dark mode is that it is AoPS specific, if it's just some generic code from Dark Reader then it would be better to just install dark reader. If you create your own dark mode code from scratch I might accept it, but seeing as AoPS Enhanced is for AoPS and only AoPS, this really makes no sense at all to merge.

**Comment by darkwater4213** [comment]
Well, that's the idea behind this. I may not have said this, but I am going to be working on this separately anyways. I'm thinking about mergng this version and the one with MaverickMan's new quote button with AoPS Master Script into a single script. I will still be pushing to this branch with darkmode updates, though.

You said that the darkmode is AoPS specific, but it really isn't; it just inverts all the colors. This darkmode makes it actually a dark AoPS, not inverted AoPS. Does that make more sense? Also, this is still incomplete.

**Comment by epiccakeking** [comment]
The current dark mode is specific to AoPS because it implements some specific code to implement dark mode. The reason it is implemented as an inversion is because it works and is simple, that doesn't make it any less specific to AoPS. Your proposed dark mode CSS is just a generic one from Dark Reader which is fairly pointless since it contains a ton of extra unrelated code and could easily be implemented by simply installing dark reader separately.

If it is incomplete, then don't ask do a merge request. I'd rather merge requests be used only for something where it is at least nearly ready to merge.

**Comment by darkwater4213** [comment]
Uh... Isn't this a draft PR? If it isn't, then you can ignore this until it's closer to done :)

**Comment by epiccakeking** [comment]
If you create a dark mode from scratch I can reopen this. If you're just going to be editing the Dark Reader code it might be better to propose changes to Dark Reader itself though.

**Comment by darkwater4213** [comment]
> If you create a dark mode from scratch I can reopen this. If you're just going to be editing the Dark Reader code it might be better to propose changes to Dark Reader itself though.

Hmm... okay, I'll delete this branch. I think I have a better idea...

**Pull request closed without merging**
