### PR TITLE
Update Quote Format

### PR DESCRIPTION
**Pull request by darkwater4213**
Updates the Quote format to MaverickMan's version: Hides the quote with the linked author's name, a "(view)" button (also linked), and replies and upvotes. (The hide tag is whatever Post # the quote is from)

### CODE REVIEW

**Comment by epiccakeking** [comment]
The current quote format is designed to be visually consistent with standard quotes while providing additional functionality (linking), maybe a "quote style selector" could be added, but I don't think it would be good to radically change the default.

**Comment by darkwater4213** [comment]
Hmm... I'll see if I can implement that. It will take a while though, because I have a few other projects running. Interesting idea, though! I'll also make sure that MaverickMan gets credit for this (their idea, not mine).

**Comment by epiccakeking** [comment]
I'm not sure if it is possible, but please separate out your proposed changes. Your proposed changes to the readme and bug report template don't make sense to be lumped in with this proposed change to the main script (also, I personally recommend Violentmonkey over Tampermonkey).

**Comment by darkwater4213** [comment]
> I'm not sure if it is possible, but please separate out your proposed changes. Your proposed changes to the readme and bug report template don't make sense to be lumped in with this proposed change to the main script (also, I personally recommend Violentmonkey over Tampermonkey).

Okay, fair enough. I find the GUI of Tamperonkey more intuitive than Violentmonkey, and it quite frankly also has a cooler logo and name ;)
I have a quick fix idea: have a separate file labeled something like aops-enhanced-2.user.js? Or maybe attribute it to MaverickMan in some way, like mm-aops-enhanced.user.js?

**Comment by epiccakeking** [comment]
If there's going to be separate versions it would probably be more practical for you to just maintain your own fork.

**Comment by darkwater4213** [comment]
Okay, I will do that. Although it would be nice if you somehow mentioned this version...? Maybe have a variations.md file that has some of the more prominent variations on this?

**Pull request closed without merging**
